# Generated by Django 5.1.7 on 2025-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
