# Generated by Django 5.1.7 on 2025-09-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_ai', '0003_conversa_alter_resposta_options_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_id', models.IntegerField(help_text='ID original do manual', unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('url_original', models.URLField()),
                ('conteudo_markdown', models.TextField(help_text='Conteúdo do manual em formato markdown')),
                ('conteudo_html_original', models.TextField(blank=True, help_text='HTML original para referência')),
                ('embedding', models.TextField(blank=True, help_text='Embedding do conteúdo para busca semântica', null=True)),
                ('total_imagens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Processado',
                'verbose_name_plural': 'Manuais Processados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagemManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField(help_text='URL original da imagem')),
                ('arquivo_imagem', models.ImageField(help_text='Arquivo da imagem salvo localmente', upload_to='manuais/imagens/')),
                ('nome_arquivo', models.CharField(help_text='Nome do arquivo gerado', max_length=255)),
                ('alt_text', models.CharField(default='Imagem', help_text='Texto alternativo da imagem', max_length=255)),
                ('ordem', models.IntegerField(help_text='Ordem da imagem no manual')),
                ('hash_conteudo', models.CharField(help_text='Hash do conteúdo da imagem para evitar duplicatas', max_length=64)),
                ('tamanho_bytes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_processado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='agent_ai.manualprocessado')),
            ],
            options={
                'verbose_name': 'Imagem do Manual',
                'verbose_name_plural': 'Imagens dos Manuais',
                'ordering': ['manual_processado', 'ordem'],
                'unique_together': {('manual_processado', 'ordem')},
            },
        ),
    ]
